#!/usr/bin/env python3
"""
Test AI metadata filtering fix for code connector parameter validation.
"""
import asyncio
import json
import sys
import os

# Add the backend directory to the Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

from app.connectors.core.code_connector import CodeConnector
from app.models.connector import ConnectorExecutionContext


async def test_ai_metadata_filtering():
    """Test that AI metadata fields are properly filtered from parameters."""
    print("🧪 Testing AI metadata filtering for code connector...")
    
    # Create code connector instance
    connector = CodeConnector()
    
    # Test parameters with AI metadata (simulating what the AI system sends)
    params_with_ai_metadata = {
        "language": "javascript",
        "mode": "runOnceForAllItems",
        "code": "return items.map(item => ({ json: { ...item.json, processed: true } }));",
        "timeout": 30,
        "safe_mode": True,
        # AI metadata fields that should be filtered out
        "_ai_confidence": 0.95,
        "_ai_explanation": "Generated JavaScript code to process items",
        "_ai_generated": True,
        "_ai_intent": "Transform data by adding processed flag",
        "_code_complexity": "simple",
        "_decision_reasoning": "User wants to process all items",
        "_risk_assessment": "low",
        "_validation": "passed"
    }
    
    print(f"📥 Original parameters: {list(params_with_ai_metadata.keys())}")
    
    # Test the filtering method directly
    filtered_params = connector._filter_auth_parameters(params_with_ai_metadata)
    
    print(f"📤 Filtered parameters: {list(filtered_params.keys())}")
    
    # Verify AI metadata was filtered out
    ai_fields = [k for k in params_with_ai_metadata.keys() if k.startswith('_ai_') or k.startswith('_')]
    remaining_ai_fields = [k for k in filtered_params.keys() if k.startswith('_ai_') or k.startswith('_')]
    
    print(f"🔍 AI metadata fields found: {ai_fields}")
    print(f"🔍 AI metadata fields remaining: {remaining_ai_fields}")
    
    # Test parameter validation with filtered parameters
    try:
        validation_result = await connector.validate_params(filtered_params)
        print(f"✅ Parameter validation passed: {validation_result}")
    except Exception as e:
        print(f"❌ Parameter validation failed: {e}")
        return False
    
    # Test execution with filtered parameters
    try:
        context = ConnectorExecutionContext(
            user_id="test_user",
            auth_tokens={},
            previous_results={
                "items": [
                    {"json": {"id": 1, "name": "test1"}},
                    {"json": {"id": 2, "name": "test2"}}
                ]
            }
        )
        
        result = await connector.execute(filtered_params, context)
        print(f"✅ Code execution successful: {result.success}")
        
        if result.success:
            print(f"📊 Result items: {len(result.data.get('items', []))}")
            if result.data.get('items'):
                print(f"📋 Sample result: {result.data['items'][0]}")
        else:
            print(f"❌ Execution error: {result.error}")
            
    except Exception as e:
        print(f"❌ Code execution failed: {e}")
        return False
    
    return True


async def test_workflow_simulation():
    """Simulate the actual workflow scenario from the logs."""
    print("\n🔄 Testing workflow simulation (Perplexity → Code → Gmail)...")
    
    # Simulate Perplexity connector output
    perplexity_output = {
        "items": [
            {
                "json": {
                    "text": "This is a sample search result about AI and machine learning. It contains information about recent developments in artificial intelligence and how machine learning algorithms are being used in various industries.",
                    "url": "https://example.com/ai-article",
                    "title": "AI and Machine Learning Trends"
                }
            },
            {
                "json": {
                    "text": "Another article about natural language processing and its applications in chatbots and virtual assistants. The technology has advanced significantly in recent years.",
                    "url": "https://example.com/nlp-article", 
                    "title": "NLP Applications"
                }
            }
        ]
    }
    
    # Code connector parameters with AI metadata (as would be generated by AI)
    code_params = {
        "language": "javascript",
        "mode": "runOnceForAllItems", 
        "code": """
// Safety check for items array
if (!Array.isArray(items)) items = [];

// Summarize all items' text fields
function summarizeText(text) {
    // Basic summarization: extract first 2 sentences, fallback to first 200 chars
    if (!text || typeof text !== 'string') return '';
    
    const sentences = text.match(/[^\.!\?]+[\.!\?]+/g);
    if (sentences && sentences.length >= 2) {
        return sentences.slice(0, 2).join(' ').trim();
    }
    return text.length > 200 ? text.slice(0, 200) + '...' : text.trim();
}

console.log('Original items:', items);

const results = items.map(item => {
    const rawText = item?.json?.text;
    const summary = summarizeText(rawText);
    
    return {
        json: {
            ...item.json,
            summary,
            summary_length: summary.length,
            original_text_length: rawText ? rawText.length : 0
        }
    };
});

console.log('Processed items with summaries:', results);
return results;
        """,
        "timeout": 30,
        "safe_mode": True,
        # AI metadata that should be filtered
        "_ai_confidence": 0.92,
        "_ai_explanation": "Generated code to summarize text from search results",
        "_ai_generated": True,
        "_ai_intent": "Process search results and create summaries",
        "_code_complexity": "intermediate",
        "_decision_reasoning": "User wants to summarize search results before emailing",
        "_risk_assessment": "low",
        "_validation": "syntax_checked"
    }
    
    # Test code connector execution
    connector = CodeConnector()
    
    try:
        # Filter parameters (this is what the base connector does)
        filtered_params = connector._filter_auth_parameters(code_params)
        
        # Validate parameters
        await connector.validate_params(filtered_params)
        print("✅ Code connector parameter validation passed")
        
        # Execute code connector
        context = ConnectorExecutionContext(
            user_id="test_user",
            auth_tokens={},
            previous_results=perplexity_output
        )
        
        result = await connector.execute(filtered_params, context)
        
        if result.success:
            print("✅ Code connector execution successful")
            print(f"📊 Processed {len(result.data.get('items', []))} items")
            
            # Show sample processed item
            if result.data.get('items'):
                sample_item = result.data['items'][0]
                print(f"📋 Sample processed item:")
                print(f"   - Original text length: {sample_item['json'].get('original_text_length', 0)}")
                print(f"   - Summary length: {sample_item['json'].get('summary_length', 0)}")
                print(f"   - Summary: {sample_item['json'].get('summary', '')[:100]}...")
            
            return result.data
        else:
            print(f"❌ Code connector execution failed: {result.error}")
            return None
            
    except Exception as e:
        print(f"❌ Code connector test failed: {e}")
        return None


async def main():
    """Run all tests."""
    print("🚀 Starting AI metadata filtering tests...\n")
    
    # Test 1: Basic AI metadata filtering
    test1_success = await test_ai_metadata_filtering()
    
    # Test 2: Workflow simulation
    test2_result = await test_workflow_simulation()
    
    print(f"\n📊 Test Results:")
    print(f"   - AI metadata filtering: {'✅ PASS' if test1_success else '❌ FAIL'}")
    print(f"   - Workflow simulation: {'✅ PASS' if test2_result else '❌ FAIL'}")
    
    if test1_success and test2_result:
        print("\n🎉 All tests passed! AI metadata filtering is working correctly.")
        return True
    else:
        print("\n❌ Some tests failed. Check the output above for details.")
        return False


if __name__ == "__main__":
    success = asyncio.run(main())
    sys.exit(0 if success else 1)